### ISSUE TITLE
Verkrijgen werkend RIBASIM test-model

### ISSUE THREAD

**Issue by d2hydro** [d2hydro/lhm-ribasim#1]
De resultante van:
- de geleverde data (forcing.arrow, model.pgkg via Deltares-ftp), opgeslagen in de repos-folder https://github.com/d2hydro/lhm-ribasim/blob/main/data/ribasim_testmodel
- project.toml, zoals in de documentatie: https://deltares.github.io/Ribasim/core/usage.html#configuration-file, zie https://github.com/d2hydro/lhm-ribasim/blob/main/data/ribasim_testmodel/config.toml
- ribasim_cli gedownload via: https://ribasim.s3.eu-west-3.amazonaws.com/teamcity/Ribasim_Ribasim/BuildRibasimCliWindows/latest/ribasim_cli.zip

Levert, naar het lijkt, een incopatible toml-file met de laatste ribasim_cli: 

![Image](https://github.com/d2hydro/lhm-ribasim/assets/43996424/5053d61f-3061-48ee-8b3a-b5b181b405f7)

**Comment by gijsber** [comment]
Hoi @d2hydro, heb je de readme gelezen ? Beste even contact opnemen met Martijn (@visr).

**Comment by visr** [comment]
Oh right, the `config.toml` in the docs still needs to be updated, the `forcing` and `Basin` are reversed, so it is:

```toml
[Basin]
forcing = "forcing.arrow"
```

We'll still make more breaking changes. So frozen models will become invalid if you use the latest executable. But ribasim-python will always be in sync in the Ribasim repository.

So it probably is a good idea to install that with ribasim_testmodels:
https://deltares.github.io/Ribasim/contribute/python.html#installing-python-packages

With that you can write test models to disk like this:
https://github.com/Deltares/Ribasim/blob/a10e0d0e2bcb95905d53b04da75eea73f6bc18cc/python/ribasim/tests/conftest.py#L32-L39
