### ISSUE TITLE
Uitkristalliseren data

### ISSUE THREAD

**Issue by d2hydro** [d2hydro/lhm-ribasim#2]
Vragen horende bij data-levering Deltares, zie: https://github.com/d2hydro/lhm-ribasim/tree/main/data

Openstaande/gesloten vragen:
- [x] Wat is LKM25?
- [x] Is verfijning LSWs_peilbegrenstNL_dec2021 de doel-resolutie voor de LHM RIBASIM schematisatie?
- [x] Willen we ook multi-resolutie kunnen rekenen? Bijvoorbeld lumpen naar districten voor een sneller rekenend model?
- [x] koppeling_lsm3_lhm3.4 is leeg, wat moet daar in?
- [x] hoe wordt linkid uit LKM links opgebouwd?

**Comment by gijsber** [comment]
LKM25 is de schematisatie van het landelijke waterkwaliteitsmodel.
districten zijn uit den boze want door vind artificiele mening van stoffen plaats, het grootste probleem dat verholpen moet worden in de basisschematisatie

**Comment by gijsber** [comment]
Is verfijning LSWs_peilbegrenstNL_dec2021 de doel-resolutie voor de LHM RIBASIM schematisatie?

antw: voorlopig wel ja, mogelijk dat we in de toekomst de kleinste peilgebieden willen combineren met een groter peilgebied

**Comment by gijsber** [comment]
Hoi @d2hydro,
Bij nader inzien denken Timo en ik dat we de verfijning peilbeheerst NL nog even in de wachtkamer zetten en dat we eerst een model met de oude LSW indeling willen hebben.  
Tevens is het goed om je te realiseren dat de Qh-relaties van Jacco vd Gaast alleen toegepast worden in hoog NL (vrijafwaterend)

**Comment by d2hydro** [comment]
@gijsber, we hebben nu LSW-routing geïmplementeerd. Kun jij gegevens aanleveren voor het mapje koppeling_lsm3_lhm3.4? Dat is een missende link tussen DM, en LKM.

**Comment by gijsber** [comment]
@d2hydro Ik heb de informatie die Sibren aan mij geleverd heeft in het desbetreffende mapje gezet

**Comment by ngoorden** [comment]
@gijsber Heb je ook deze file: DMMZtoSobekid.txt   
Komt uit de memo van Geert: docu/MemoLSW-LSMkoppeling_aanvoer.docx

**Comment by gijsber** [comment]
zie: /lhm4.3/dm/txtfiles_git/Dm_Sobek.txt

**Comment by gijsber** [comment]
op de ftp site staat een gestandaardiseerd invoerbestand met per LWS een SAQh relatie die gesplitst moet worden in een SAh en een QH-relatie:
ftps://ftp.deltares.nl/brondata/ribasim_testmodel/simplified_SAQh.nc
Q is non-zero voor vrijafwaterende LSWs

**Comment by gijsber** [comment]
LSM obese data staat op: /brondata/LSM_obsese/

**Comment by ngoorden** [comment]
@gijsber; kunnen jullie ook de case-dir van het LSM_obese model sturen? We willen graag meer uit het netwerk halen en hebben daarvoor een reader.

**Comment by gijsber** [comment]
@ngoorden: posted on FTP-site: ftps://ftp.deltares.nl/brondata/LSM_obese/LSMKRW.lit

**Comment by d2hydro** [comment]
Voor deze fase geen nieuwe data meer nodig
