### ISSUE TITLE
dataherkomst registratie in extra kolom van netwerk

### ISSUE THREAD

**Issue by gijsber** [d2hydro/lhm-ribasim#3]
Het zou mooi zijn als in het geopackage voor elke node/edge in een extra veld (ORIGIN) wordt bijgehouden wat de dataherkomst is.
bijv. MZlsw_<lswnr>
DMnd_<nodenr>
DMlk_<linknr>
etc.

**Comment by d2hydro** [comment]
We pakken dit mee in #5

**Comment by d2hydro** [comment]
Alle links en nodes in het LHM netwerk zijn duidelijk herleidbaar naar LSWs, DM of de link tussen beiden (kolom `index`) volgend voorgesteld schema, zie: https://d2hydro.github.io/lhm-ribasim/notebooks/bouw_lhm_netwerk/#3-opbouw-lhm-netwerk.

We nemen de index mee in RIBASIM in de kolom `lhm_index`
