### ISSUE TITLE
Ribasim.jl editable installatie

### ISSUE THREAD

**Issue by d2hydro** [d2hydro/lhm-ribasim#8]
Doel: opzetten editable installatie voor @d2hydro

## Installatie
Uitgevoerd tot https://deltares.github.io/Ribasim/contribute/core.html#sec-test.

`julia --project=core`

levert volgende foutmelding:

![Image](https://user-images.githubusercontent.com/43996424/248753386-1457aa2c-bb2d-4c2c-a5c5-20436fc047a8.png)

lijkt er verder wel goed door te komen:

![Image](https://user-images.githubusercontent.com/43996424/248756717-0a95316e-aa6b-4dbf-a508-c5bdc661d64c.png)

## Bijgeleverde test-modellen
Wanneer ik `pkg> test` uitvoer in de root van de repos, bij mij `D:\\repositories` dan krijg ik een error met de volgende stacktrace:

![Image](https://user-images.githubusercontent.com/43996424/248774944-aab49122-71a0-4757-bf16-a2bb6a7899df.png)

`D:\\repositories\\ribasim\\data\\trivial\\trivial.toml` bestaat idd niet, `d:\repositories\ribasim\python\ribasim\tests\data\trivial\\trivial.toml` wel. Ik neem aan dat er iets fout is gegaan bij draaien "d:\repositories\ribasim\python\ribasim\tests\conftest.py", aangezien de verwachtte locatie een logische is.

work-around, inhoud van d:\repositories\ribasim\python\ribasim\tests\data ->  d:\repositories\ribasim\data gekopieerd.

Levert resultaat
![Image](https://user-images.githubusercontent.com/43996424/248778229-4294f145-3da0-4eec-9ab7-81b1e43844d0.png)

## Flevoland-model
Uitvoeren dit stuk: https://deltares.github.io/Ribasim/contribute/core.html#run-ribasim-simulations

Ribasim.run("d://repositories//lhm-ribasim//data//ribasim_model_flevoland//ribasim_model_flevoland.toml") levert:

![Image](https://github.com/d2hydro/lhm-ribasim/assets/43996424/232d1f6f-5748-4f85-9ef9-a0f527b4c13e)

**Comment by d2hydro** [comment]
@visr, zie description; hoe krijg ik mijn test-data automatisch in het juiste mapje?

**Comment by visr** [comment]
Het pad is t.o.v. je workdir. Wij gebruiken meestal de repo root als workdir.

https://github.com/Deltares/Ribasim/blob/586c2c04a649f47193b2fa2a4d63e082533100b6/python/ribasim/tests/conftest.py#L38

Dus als je `python python/ribasim/tests/conftest.py` draait vanuit de repo root, dan komt je test data onder ./data.

**Comment by d2hydro** [comment]
closed; werkt sinds 26-06
